# Pull from python3.11 image
FROM python:3.10-bookworm

RUN apt-get -y update && apt-get -y upgrade


RUN git clone https://github.com/dream-aim-deliver/kernel-planckster.git /kernel-planckster

WORKDIR /kernel-planckster

RUN pip install poetry
RUN poetry install


# Install docker client
RUN apt-get update -y && \
    apt-get install -y ca-certificates curl gnupg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update -y && \
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin


ENTRYPOINT ["/bin/bash"]