"""Add external ID

Revision ID: 3bdadc507473
Revises: 7a54088140e6
Create Date: 2024-11-02 14:03:58.728300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3bdadc507473"
down_revision: Union[str, None] = "7a54088140e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("research_context", sa.Column("external_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("research_context", "external_id")
    # ### end Alembic commands ###
