"""remove testing dummy table

Revision ID: 5bbe420103fe
Revises: 943b1eb7b423
Create Date: 2024-08-14 12:18:25.144935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bbe420103fe'
down_revision: Union[str, None] = '943b1eb7b423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dummy_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('created_at IS NOT NULL', name='DUMMY_TABLE_CREATED_NN'),
    sa.CheckConstraint('deleted IS NOT NULL', name='DUMMY_TABLE_DELETED_NN'),
    sa.CheckConstraint('updated_at IS NOT NULL', name='DUMMY_TABLE_UPDATED_NN'),
    sa.PrimaryKeyConstraint('id', name='dummy_table_pkey'),
    sa.UniqueConstraint('dummy_name', name='dummy_table_dummy_name_key')
    )
    # ### end Alembic commands ###
