"""separate message contents from metadata

Revision ID: 6e3d1bbe150b
Revises: 76f97f40e847
Create Date: 2024-09-27 08:58:32.474629

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e3d1bbe150b"
down_revision: Union[str, None] = "76f97f40e847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("content_type", sa.Enum("TEXT", "IMAGE", name="messagecontenttypeenum"), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="MESSAGE_CONTENT_CREATED_NN"),
        sa.CheckConstraint("DELETED IS NOT NULL", name="MESSAGE_CONTENT_DELETED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="MESSAGE_CONTENT_UPDATED_NN"),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message_base.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.add_column("message_base", sa.Column("thread_id", sa.Integer(), nullable=False))
    op.drop_column("message_base", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message_base", sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("message_base", "thread_id")
    op.drop_table("message_content")
    # These were added by hand
    # We need to manually drop the enums created in the upgrade
    sa_enum_messagecontenttypeenum = sa.Enum(name="messagecontenttypeenum")
    sa_enum_messagecontenttypeenum.drop(op.get_bind(), checkfirst=True)  # type: ignore
    # ### end Alembic commands ###
