"""initialization

Revision ID: 76f97f40e847
Revises: 
Create Date: 2024-03-24 01:51:05.319023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76f97f40e847"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # For each polymorphic child (messages), we need to manually delete all the sa.CheckConstraint(...) lines
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub", sa.String(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="CLIENT_CREATED_NN"),
        sa.CheckConstraint("DELETED IS NOT NULL", name="CLIENT_DELETED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="CLIENT_UPDATED_NN"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sub"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "embedding_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="EMBEDDING_MODEL_CREATED_NN"),
        sa.CheckConstraint("DELETED IS NOT NULL", name="EMBEDDING_MODEL_DELETED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="EMBEDDING_MODEL_UPDATED_NN"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "llm",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("llm_name", sa.String(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="LLM_CREATED_NN"),
        sa.CheckConstraint("DELETED IS NOT NULL", name="LLM_DELETED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="LLM_UPDATED_NN"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("llm_name"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "embedding_model_llm_association",
        sa.Column("embedding_model_id", sa.Integer(), nullable=True),
        sa.Column("llm_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["embedding_model_id"],
            ["embedding_model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_id"],
            ["llm.id"],
        ),
    )
    op.create_table(
        "research_context",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("llm_id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="RESEARCH_CONTEXT_CREATED_NN"),
        sa.CheckConstraint("DELETED IS NOT NULL", name="RESEARCH_CONTEXT_DELETED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="RESEARCH_CONTEXT_UPDATED_NN"),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_id"],
            ["llm.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "source_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("relative_path", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("protocol", sa.Enum("S3", "NAS", "LOCAL", name="protocolenum"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CREATED", "UNAVAILABLE", "AVAILABLE", "INCONSISTENT_DATASET", name="sourcedatastatusenum"),
            nullable=False,
        ),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uix_client_id_relative_path_protocol", "source_data", ["client_id", "relative_path", "protocol"], unique=True
    )
    op.create_table(
        "conversation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("research_context_id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="CONVERSATION_CREATED_NN"),
        sa.CheckConstraint("DELETED IS NOT NULL", name="CONVERSATION_DELETED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="CONVERSATION_UPDATED_NN"),
        sa.ForeignKeyConstraint(
            ["research_context_id"],
            ["research_context.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "source_data_research_context_association",
        sa.Column("source_data_id", sa.Integer(), nullable=True),
        sa.Column("research_context_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["research_context_id"],
            ["research_context.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_data_id"],
            ["source_data.id"],
        ),
    )
    op.create_table(
        "vector_store",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lfn", sa.String(), nullable=False),
        sa.Column("research_context_id", sa.Integer(), nullable=True),
        sa.Column("embedding_model_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="VECTOR_STORE_CREATED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="VECTOR_STORE_UPDATED_NN"),
        sa.ForeignKeyConstraint(
            ["embedding_model_id"],
            ["embedding_model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_context_id"],
            ["research_context.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lfn"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "message_base",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="MESSAGE_BASE_CREATED_NN"),
        sa.CheckConstraint("DELETED IS NOT NULL", name="MESSAGE_BASE_DELETED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="MESSAGE_BASE_UPDATED_NN"),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "agent_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["message_base.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["message_base.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "citation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_data_id", sa.Integer(), nullable=False),
        sa.Column("citation_metadata", sa.String(), nullable=False),
        sa.Column("agent_message_id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="CITATION_CREATED_NN"),
        sa.CheckConstraint("DELETED IS NOT NULL", name="CITATION_DELETED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="CITATION_UPDATED_NN"),
        sa.ForeignKeyConstraint(
            ["agent_message_id"],
            ["agent_message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_data_id"],
            ["source_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("citation")
    op.drop_table("user_message")
    op.drop_table("agent_message")
    op.drop_table("message_base")
    op.drop_table("vector_store")
    op.drop_table("source_data_research_context_association")
    op.drop_table("conversation")
    op.drop_index("uix_client_id_relative_path_protocol", table_name="source_data")
    op.drop_table("source_data")
    op.drop_table("research_context")
    op.drop_table("embedding_model_llm_association")
    op.drop_table("llm")
    op.drop_table("embedding_model")
    op.drop_table("client")
    # These were added by hand
    # We need to manually drop the enums created in the upgrade
    sa_enum_sourcedatastatusenum = sa.Enum(name="sourcedatastatusenum")
    sa_enum_sourcedatastatusenum.drop(op.get_bind(), checkfirst=True)  # type: ignore
    sa_enum_protocolenum = sa.Enum(name="protocolenum")
    sa_enum_protocolenum.drop(op.get_bind(), checkfirst=True)  # type: ignore
    # ### end Alembic commands ###
