"""testing with dummy table

Revision ID: 943b1eb7b423
Revises: 76f97f40e847
Create Date: 2024-08-14 11:29:35.769373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943b1eb7b423'
down_revision: Union[str, None] = '76f97f40e847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dummy_name', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('CREATED_AT IS NOT NULL', name='DUMMY_TABLE_CREATED_NN'),
    sa.CheckConstraint('DELETED IS NOT NULL', name='DUMMY_TABLE_DELETED_NN'),
    sa.CheckConstraint('UPDATED_AT IS NOT NULL', name='DUMMY_TABLE_UPDATED_NN'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dummy_name'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_table')
    # ### end Alembic commands ###
